(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var q;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ca(this);function u(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.g=g;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});function da(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ka={};try{ka.__proto__=ia;ha=ka.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var la=fa;function x(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(la)la(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype}function ma(){this.j=!1;this.h=null;this.l=void 0;this.g=1;this.s=0;this.i=null}function na(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}ma.prototype.o=function(a){this.l=a};
function oa(a,b){a.i={U:b,V:!0};a.g=a.s}ma.prototype.return=function(a){this.i={return:a};this.g=this.s};function pa(a){this.g=new ma;this.h=a}function qa(a,b){na(a.g);var c=a.g.h;if(c)return ra(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return y(a)}
function ra(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.j=!1,e;var g=e.value}catch(f){return a.g.h=null,oa(a.g,f),y(a)}a.g.h=null;d.call(a.g,g);return y(a)}function y(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(c){a.g.l=void 0,oa(a.g,c)}a.g.j=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.V)throw b.U;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function sa(a){this.next=function(b){na(a.g);a.g.h?b=ra(a,a.g.h.next,b,a.g.o):(a.g.o(b),b=y(a));return b};this.throw=function(b){na(a.g);a.g.h?b=ra(a,a.g.h["throw"],b,a.g.o):(oa(a.g,b),b=y(a));return b};this.return=function(b){return qa(a,b)};this[Symbol.iterator]=function(){return this}}function ta(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
function ua(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.s=!1;var h=this.j();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(f)};var e=r.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var h=0;h<f.length;++h){var k=
f[h];f[h]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:f(this.D),reject:f(this.l)}};b.prototype.D=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.G(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.C(f):this.o(f)}};
b.prototype.C=function(f){var h=void 0;try{h=f.then}catch(k){this.l(k);return}"function"==typeof h?this.H(h,f):this.o(f)};b.prototype.l=function(f){this.u(2,f)};b.prototype.o=function(f){this.u(1,f)};b.prototype.u=function(f,h){if(0!=this.h)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.h);this.h=f;this.i=h;2===this.h&&this.F();this.B()};b.prototype.F=function(){var f=this;e(function(){if(f.K()){var h=r.console;"undefined"!==typeof h&&h.error(f.i)}},1)};b.prototype.K=
function(){if(this.s)return!1;var f=r.CustomEvent,h=r.Event,k=r.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=r.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.B=function(){if(null!=this.g){for(var f=0;f<this.g.length;++f)g.h(this.g[f]);this.g=null}};var g=new c;b.prototype.G=
function(f){var h=this.j();f.I(h.resolve,h.reject)};b.prototype.H=function(f,h){var k=this.j();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,h){function k(p,t){return"function"==typeof p?function(v){try{l(p(v))}catch(B){m(B)}}:t}var l,m,n=new b(function(p,t){l=p;m=t});this.I(k(f,l),k(h,m));return n};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.I=function(f,h){function k(){switch(l.h){case 1:f(l.i);break;case 2:h(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;null==this.g?g.h(k):this.g.push(k);this.s=!0};b.resolve=d;b.reject=function(f){return new b(function(h,k){k(f)})};b.race=function(f){return new b(function(h,k){for(var l=w(f),m=l.next();!m.done;m=l.next())d(m.value).I(h,k)})};b.all=function(f){var h=w(f),k=h.next();return k.done?d([]):new b(function(l,m){function n(v){return function(B){p[v]=B;t--;0==t&&l(p)}}var p=[],t=0;do p.push(void 0),t++,d(k.value).I(n(p.length-1),m),k=h.next();while(!k.done)})};return b});
function va(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.entries",function(a){return a?a:function(){return va(this,function(b,c){return[b,c]})}});
u("String.prototype.startsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.startsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.startsWith must not be a regular expression");var d=this.length,e=b.length;c=Math.max(0,Math.min(c|0,this.length));for(var g=0;g<e&&c<d;)if(this[c++]!=b[g++])return!1;return g>=e}});
u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}});var z=this||self;function wa(a){var b=a.url;a=a.O;this.j=b;this.o=a;a=/[?&]dsh=1(&|$)/.test(b);this.h=!a&&/[?&]ae=1(&|$)/.test(b);this.l=!a&&/[?&]ae=2(&|$)/.test(b);if((this.g=/[?&]adurl=([^&]*)/.exec(b))&&this.g[1]){try{var c=decodeURIComponent(this.g[1])}catch(d){c=null}this.i=c}}function xa(a){var b="&act=1&ri=1";a.h&&a.o&&(b+=ya(a));return za(a,b)}function Aa(a,b){return a.h&&a.i||a.l?1==b?a.h?a.i:za(a,"&dct=1"):2==b?za(a,"&ri=2"):za(a,"&ri=16"):a.j}
function za(a,b){return a.g?a.j.slice(0,a.g.index)+b+a.j.slice(a.g.index):a.j+b}
function ya(a){a=a.o;var b=encodeURIComponent,c="";a.platform&&(c+="&uap="+b(a.platform));a.platformVersion&&(c+="&uapv="+b(a.platformVersion));a.uaFullVersion&&(c+="&uafv="+b(a.uaFullVersion));a.architecture&&(c+="&uaa="+b(a.architecture));a.model&&(c+="&uam="+b(a.model));a.bitness&&(c+="&uab="+b(a.bitness));a.fullVersionList&&(c+="&uafvl="+b(a.fullVersionList.map(function(d){return b(d.brand)+";"+b(d.version)}).join("|")));"undefined"!==typeof a.wow64&&(c+="&uaw="+Number(a.wow64));return c};function A(a){var b;a:{if(b=z.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function C(a,b){this.g=b===Ba?a:""}C.prototype.i=!0;C.prototype.h=function(){return this.g.toString()};C.prototype.toString=function(){return this.g.toString()};function Ca(a){return a instanceof C&&a.constructor===C?a.g:"type_error:SafeUrl"}var Da=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Ba={};var Ea=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Fa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Ga(a,b){a:{for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Ha={};function Ia(){}function D(a){this.g=a}x(D,Ia);D.prototype.toString=function(){return this.g};var Ja=new D("about:invalid#zTSz",Ha);function Ka(a){if(a instanceof Ia)if(a instanceof D)a=a.g;else throw Error("");else a=Ca(a);return a};function La(a){this.W=a}function E(a){return new La(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Ma=new La(function(a){return/^[^:]*([/?#]|$)/.test(a)}),Na=E("http"),Oa=E("https"),Pa=E("ftp"),Qa=E("mailto"),Ra=E("intent"),Sa=E("market"),Ta=E("itms"),Ua=E("itms-appss"),Va=[E("data"),Na,Oa,Qa,Pa,Ma];function Wa(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function Xa(a,b){b instanceof C||b instanceof C||(b="object"==typeof b&&b.i?b.h():String(b),Da.test(b)||(b="about:invalid#zClosurez"),b=new C(b,Ba));a.href=Ca(b)};function Ya(){return A("iPhone")&&!A("iPod")&&!A("iPad")};function Za(a){Za[" "](a);return a}Za[" "]=function(){};var $a=Ya(),ab=A("iPad");var bb=Ya()||A("iPod"),cb=A("iPad");var fb={},gb=null;
function ib(a,b){void 0===b&&(b=0);if(!gb){gb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));fb[e]=g;for(var f=0;f<g.length;f++){var h=g[f];void 0===gb[h]&&(gb[h]=f)}}}b=fb[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var k=a[g],l=a[g+1];h=a[g+2];f=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[e++]=f+k+l+h}f=0;h=d;switch(a.length-g){case 2:f=
a[g+1],h=b[(f&15)<<2]||d;case 1:a=a[g],c[e]=b[a>>2]+b[(a&3)<<4|f>>4]+h+d}return c.join("")};var jb="undefined"!==typeof Uint8Array;var F="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function kb(a,b){Object.isFrozen(a)||(F?a[F]|=b:void 0!==a.J?a.J|=b:Object.defineProperties(a,{J:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function lb(a){var b;F?b=a[F]:b=a.J;return null==b?0:b}function G(a){kb(a,1);return a}function H(a){return Array.isArray(a)?!!(lb(a)&2):!1}function I(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");kb(a,2)};function nb(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var ob,pb=Object.freeze(G([]));function qb(a){if(H(a.m))throw Error("Cannot mutate an immutable Message");}var rb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function sb(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function J(a,b){this.g=a;this.i=b;this.map={};this.h=!1;for(a=this.size=0;a<this.g.length;a++){b=this.g[a];var c=b[0].toString(),d=this.map[c];this.map[c]=b;void 0===d&&this.size++}}q=J.prototype;q.v=function(){if(!this.h){var a=tb(this);a.sort();for(var b=0;b<a.length;b++)this.g[b]=this.map[a[b]];a.length<this.g.length&&(this.g.length=a.length);this.h=!0;this.size=this.g.length}return this.g};
q.entries=function(){var a=[],b=tb(this);b.sort();for(var c=0;c<b.length;c++){var d=this.map[b[c]];a.push([d[0],ub(this,d)])}return new vb(a)};q.keys=function(){var a=[],b=tb(this);b.sort();for(var c=0;c<b.length;c++)a.push(this.map[b[c]][0]);return new vb(a)};q.values=function(){var a=[],b=tb(this);b.sort();for(var c=0;c<b.length;c++)a.push(ub(this,this.map[b[c]]));return new vb(a)};
q.forEach=function(a,b){var c=tb(this);c.sort();for(var d=0;d<c.length;d++){var e=this.map[c[d]];a.call(b,ub(this,e),e[0],this)}};q.set=function(a,b){if(H(this.g))throw Error("Cannot mutate an immutable Map");var c=a.toString(),d=this.map[c];d?d[1]=b:(a=[a,b],this.map[c]=a,this.g.push(a),this.h=!1,this.size++);return this};function ub(a,b){var c=b[1];a.i&&(Array.isArray(c)||null==c)&&(c=new a.i(c),c=b[1]=c,H(a.g)&&I(c.m));return c}q.get=function(a){if(a=this.map[a.toString()])return ub(this,a)};
q.has=function(a){return a.toString()in this.map};function tb(a){a=a.map;var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}J.prototype[Symbol.iterator]=function(){return this.entries()};function vb(a){this.h=0;this.g=a}vb.prototype.next=function(){return this.h<this.g.length?{done:!1,value:this.g[this.h++]}:{done:!0,value:void 0}};vb.prototype[Symbol.iterator]=function(){return this};function wb(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(jb&&null!=a&&a instanceof Uint8Array)return ib(a);if(a instanceof J)return a.v()}}return a};function xb(a,b){b=void 0===b?yb:b;return zb(a,b)}function Ab(a,b){if(null!=a){if(Array.isArray(a))a=zb(a,b);else if(nb(a)){var c={},d;for(d in a)c[d]=Ab(a[d],b);a=c}else a=b(a);return a}}function zb(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=Ab(c[d],b);Array.isArray(a)&&lb(a)&1&&G(c);return c}function Bb(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=wb(a);return Array.isArray(a)?xb(a,Bb):a}function Cb(a){return Db(a)}
function yb(a){if(jb&&null!=a&&a instanceof Uint8Array)a=new Uint8Array(a);else if(a instanceof J){var b=Cb,c=a.i,d=new J(G([]),c),e;for(e in a.map){var g=a.map[e];c?d.set(g[0],b(ub(a,g))):d.set(g[0],g[1])}a=d}return a};function K(a,b,c){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:(void 0===c?0:c)&&a.h&&(c=a.h[b],null!=c)?c:a.m[b+a.i]}function M(a,b,c,d,e){d=void 0===d?!1:d;(void 0===e?0:e)||qb(a);b<a.j&&!d?a.m[b+a.i]=c:(a.h||(a.h=a.m[a.j+a.i]={}))[b]=c;return a}function Eb(a,b,c,d){c=void 0===c?!0:c;d=void 0===d?!1:d;var e=K(a,b,d);null==e&&(e=pb);if(H(a.m))c&&(I(e),Object.freeze(e));else if(e===pb||H(e))e=G(e.slice()),M(a,b,e,d);return e}function N(a,b,c){a=K(a,b);return null==a?c:a}
function O(a,b){a=K(a,b);a=null==a?a:!!a;return null==a?!1:a}function Fb(a,b,c){a:{var d=K(a,b);if(null==d)d=[];else if(d.constructor===J){a=d;break a}var e=H(a.m),g=H(d);if(!e&&g){for(var f=d.slice(),h=0;h<d.length;h++)if(Array.isArray(f[h])){var k=f[h].slice();f[h]=k;c&&1<k.length&&Array.isArray(k[1])&&I(k[1])}d=f}c=new J(d,c);e&&!g&&I(c.g);M(a,b,c,!1,!0);a=c}return a}
function P(a,b,c,d,e){if(-1===c)return null;a.g||(a.g={});var g=a.g[c];if(g)return g;e=K(a,c,void 0===e?!1:e);if(null==e&&!d)return g;b=new b(e);H(a.m)&&I(b.m);return a.g[c]=b}function Gb(a,b,c,d){a.g||(a.g={});var e=H(a.m),g=a.g[c];if(!g){d=Eb(a,c,!0,void 0===d?!1:d);g=[];e=e||H(d);for(var f=0;f<d.length;f++)g[f]=new b(d[f]),e&&I(g[f].m);e&&(I(g),Object.freeze(g));a.g[c]=g}return g}function Q(a,b){return N(a,b,"")};function Hb(a,b,c){a||(a=Ib);Ib=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.i=(d?0:-1)-(this.constructor.g||0);this.g=void 0;this.m=a;a:{d=this.m.length;a=d-1;if(d&&(d=this.m[a],nb(d))){this.j=a-this.i;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.i),this.h=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.i,(d=this.m[a])?Array.isArray(d)&&G(d):this.m[a]=pb;else{d=this.h||(this.h=this.m[this.j+this.i]={});var e=d[a];e?Array.isArray(e)&&G(e):
d[a]=pb}}Hb.prototype.toJSON=function(){var a=this.v();return ob?a:xb(a,Bb)};Hb.prototype.v=function(){return this.m};function Jb(a){ob=!0;try{return JSON.stringify(a.toJSON(),Kb)}finally{ob=!1}}function Db(a){var b=xb(a.v());Ib=b;b=new a.constructor(b);Ib=null;Lb(b,a);return b}Hb.prototype.toString=function(){return this.v().toString()};function Kb(a,b){return wb(b)}
function Lb(a,b){b.l&&(a.l=b.l.slice());var c=b.g;if(c){b=b.h;for(var d in c){var e=c[d];if(e){var g=!(!b||!b[d]),f=+d;if(Array.isArray(e)){if(e.length)for(g=Gb(a,e[0].constructor,f,g),f=0;f<Math.min(g.length,e.length);f++)Lb(g[f],e[f])}else(g=P(a,e.constructor,f,void 0,g))&&Lb(g,e)}}}}var Ib;function Mb(){Hb.apply(this,arguments)}x(Mb,Hb);if(rb){var Nb={};Object.defineProperties(Mb,(Nb[Symbol.hasInstance]=sb(function(){throw Error("Cannot perform instanceof checks for MutableMessage");}),Nb))};function S(){Mb.apply(this,arguments)}x(S,Mb);if(rb){var Ob={};Object.defineProperties(S,(Ob[Symbol.hasInstance]=sb(Object[Symbol.hasInstance]),Ob))};function Pb(a){S.call(this,a)}x(Pb,S);function Qb(a){S.call(this,a)}x(Qb,S);function Rb(a){S.call(this,a,-1,Sb)}x(Rb,S);function T(a){S.call(this,a)}x(T,S);T.prototype.A=function(){return Q(this,3)};T.prototype.N=function(a){M(this,5,a)};function U(a){S.call(this,a)}x(U,S);U.prototype.A=function(){return Q(this,1)};U.prototype.N=function(a){M(this,2,a)};function Tb(a){S.call(this,a)}x(Tb,S);var Sb=[6,7];function Ub(a){S.call(this,a,-1,Vb)}x(Ub,S);var Vb=[17];function Wb(a){S.call(this,a)}x(Wb,S);var Xb={capture:!0},Yb={passive:!0},Zb=Wa(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});z.addEventListener("test",null,b)}catch(c){}return a});function $b(a){return a?a.passive&&Zb()?a:a.capture||!1:!1}function ac(a,b,c,d){a.addEventListener&&a.addEventListener(b,c,$b(d))};function bc(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36)};var cc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function dc(a){var b=a.indexOf("#");0>b&&(b=a.length);var c=a.indexOf("?");if(0>c||c>b){c=b;var d=""}else d=a.substring(c+1,b);return[a.slice(0,c),d,a.slice(b)]}function ec(a,b){return b?a?a+"&"+b:b:a}function fc(a,b){if(!b)return a;a=dc(a);a[1]=ec(a[1],b);return a[0]+(a[1]?"?"+a[1]:"")+a[2]}
function gc(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)gc(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}function hc(a){var b=[],c;for(c in a)gc(c,a[c],b);return b.join("&")}var ic=/#|$/;function jc(a,b){a=dc(a);var c=a[1],d=[];c&&c.split("&").forEach(function(e){var g=e.indexOf("=");b.hasOwnProperty(0<=g?e.slice(0,g):e)||d.push(e)});a[1]=ec(d.join("&"),hc(b));return a[0]+(a[1]?"?"+a[1]:"")+a[2]};function kc(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}var lc=[];function mc(){var a=lc;lc=[];a=w(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;try{b()}catch(c){}}}function nc(a){lc.push(a);1==lc.length&&(window.Promise?Promise.resolve().then(mc):window.setImmediate?setImmediate(mc):setTimeout(mc,0))}function oc(a){var b=W;"complete"===b.readyState||"interactive"===b.readyState?nc(a):b.addEventListener("DOMContentLoaded",a)}
function pc(a){var b=window;"complete"===b.document.readyState?nc(a):b.addEventListener("load",a)}function qc(a){a=void 0===a?document:a;return a.createElement("img")};function vc(a,b,c,d){wc(a,b,void 0===c?null:c,void 0===d?!1:d)}function wc(a,b,c,d){a.google_image_requests||(a.google_image_requests=[]);var e=qc(a.document);if(c||d){var g=function(f){c&&c(f);if(d){f=a.google_image_requests;var h=Ea(f,e);0<=h&&Array.prototype.splice.call(f,h,1)}e.removeEventListener&&e.removeEventListener("load",g,$b());e.removeEventListener&&e.removeEventListener("error",g,$b())};ac(e,"load",g);ac(e,"error",g)}e.src=b;a.google_image_requests.push(e)}
function xc(a,b){var c=void 0===c?!1:c;var d;if(d=a.navigator)d=a.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&a.navigator.sendBeacon?a.navigator.sendBeacon(b):vc(a,b,void 0,c)};var yc=0;function zc(a){return(a=Ac(a))&&a.getAttribute("data-jc-version")||"unknown"}function Ac(a){var b=document.currentScript;return(b=void 0===b?null:b)&&b.getAttribute("data-jc")===String(a)?b:document.querySelector('[data-jc="'+a+'"]')}
function Bc(a){var b=void 0===b?.01:b;if(!(Math.random()>b)){var c=Ac(a);a="https://"+(c&&"true"===c.getAttribute("data-jc-rcd")?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc="+a+"&version="+zc(a)+"&sample="+b;xc(window,a)}};var W=document,X=window;var Cc=[Na,Oa,Qa,Pa,Ma,Sa,Ta,Ra,Ua];function Dc(a,b){if(a instanceof C)return a;var c=Cc;c=void 0===c?Va:c;a:{c=void 0===c?Va:c;for(var d=0;d<c.length;++d){var e=c[d];if(e instanceof La&&e.W(a)){c=new D(a,Ha);break a}}c=void 0}c=c||Ja;c===Ja&&b(a);return new C(Ka(c),Ba)}function Ec(a){var b=(Fc()?"http:":"https:")+"//pagead2.googlesyndication.com/pagead/gen_204";return function(c){c=hc({id:"unsafeurl",ctx:a,url:c});c=fc(b,c);navigator.sendBeacon&&navigator.sendBeacon(c,"")}};function Fc(){var a=void 0===a?X:a;return"http:"===a.location.protocol}function Gc(a){var b=W;try{return b.querySelectorAll("*["+a+"]")}catch(c){return[]}};function Hc(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};var Ic=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");function Jc(a,b){this.g=a;this.h=b}function Kc(a,b){this.url=a;this.M=!!b;this.depth=null};function Lc(){this.i="&";this.h={};this.j=0;this.g=[]}function Mc(a,b){var c={};c[a]=b;return[c]}function Nc(a,b,c,d,e){var g=[];kc(a,function(f,h){(f=Oc(f,b,c,d,e))&&g.push(h+"="+f)});return g.join(b)}
function Oc(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var g=[],f=0;f<a.length;f++)g.push(Oc(a[f],b,c,d+1,e));return g.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Nc(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function Pc(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;var d=Qc(a)-c.length;if(0>d)return"";a.g.sort(function(m,n){return m-n});c=null;for(var e="",g=0;g<a.g.length;g++)for(var f=a.g[g],h=a.h[f],k=0;k<h.length;k++){if(!d){c=null==c?f:c;break}var l=Nc(h[k],a.i,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;b+=l;e=a.i;break}c=null==c?f:c}}a="";null!=c&&(a=e+"trn="+c);return b+a}function Qc(a){var b=1,c;for(c in a.h)b=c.length>b?c.length:b;return 3997-b-a.i.length-1};function Rc(){this.h=Fc()?"http:":"https:";this.g=Math.random()}function Sc(){var a=Tc,b=window.google_srt;0<=b&&1>=b&&(a.g=b)}function Uc(a,b,c,d,e){if((d?a.g:Math.random())<(e||.01))try{if(c instanceof Lc)var g=c;else g=new Lc,kc(c,function(h,k){var l=g,m=l.j++;h=Mc(k,h);l.g.push(m);l.h[m]=h});var f=Pc(g,a.h,"/pagead/gen_204?id="+b+"&");f&&vc(z,f)}catch(h){}};var Vc=null;function Wc(){var a=void 0===a?z:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function Xc(){var a=void 0===a?z:a;return(a=a.performance)&&a.now?a.now():null};function Yc(a,b){var c=Xc()||Wc();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.taskId=this.slotId=void 0};var Y=z.performance,Zc=!!(Y&&Y.mark&&Y.measure&&Y.clearMarks),$c=Wa(function(){var a;if(a=Zc){var b;if(null===Vc){Vc="";try{a="";try{a=z.top.location.hash}catch(c){a=z.location.hash}a&&(Vc=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Vc;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
function ad(){var a=window;this.h=[];this.i=a||z;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=$c()||(null!=b?b:1>Math.random())}function bd(a){a&&Y&&$c()&&(Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),Y.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}ad.prototype.start=function(a,b){if(!this.g)return null;a=new Yc(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";Y&&$c()&&Y.mark(b);return a};
ad.prototype.end=function(a){if(this.g&&"number"===typeof a.value){a.duration=(Xc()||Wc())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";Y&&$c()&&Y.mark(b);!this.g||2048<this.h.length||this.h.push(a)}};function cd(){var a=dd;this.i=Tc;this.h=null;this.o=this.l;this.g=void 0===a?null:a;this.j=!1}cd.prototype.pinger=function(){return this.i};function ed(a,b){var c=fd;try{if(c.g&&c.g.g){var d=c.g.start(a.toString(),3);var e=b();c.g.end(d)}else e=b()}catch(h){b=!0;try{bd(d),b=c.o(a,new Hc(h,{message:gd(h)}),void 0,void 0)}catch(k){c.l(217,k)}if(b){var g,f;null==(g=window.console)||null==(f=g.error)||f.call(g,h)}else throw h;}return e}
function hd(a,b){return function(){var c=ua.apply(0,arguments);return ed(a,function(){return b.apply(void 0,c)})}}
cd.prototype.l=function(a,b,c,d,e){e=e||"jserror";try{var g=new Lc;g.g.push(1);g.h[1]=Mc("context",a);b.error&&b.meta&&b.id||(b=new Hc(b,{message:gd(b)}));if(b.msg){var f=b.msg.substring(0,512);g.g.push(2);g.h[2]=Mc("msg",f)}var h=b.meta||{};if(this.h)try{this.h(h)}catch(V){}if(d)try{d(h)}catch(V){}b=[h];g.g.push(3);g.h[3]=b;d=z;b=[];f=null;do{var k=d;try{var l;if(l=!!k&&null!=k.location.href)b:{try{Za(k.foo);l=!0;break b}catch(V){}l=!1}var m=l}catch(V){m=!1}if(m){var n=k.location.href;f=k.document&&
k.document.referrer||null}else n=f,f=null;b.push(new Kc(n||""));try{d=k.parent}catch(V){d=null}}while(d&&k!=d);n=0;for(var p=b.length-1;n<=p;++n)b[n].depth=p-n;k=z;if(k.location&&k.location.ancestorOrigins&&k.location.ancestorOrigins.length==b.length-1)for(p=1;p<b.length;++p){var t=b[p];t.url||(t.url=k.location.ancestorOrigins[p-1]||"",t.M=!0)}var v=new Kc(z.location.href,!1);k=null;var B=b.length-1;for(t=B;0<=t;--t){var L=b[t];!k&&Ic.test(L.url)&&(k=L);if(L.url&&!L.M){v=L;break}}L=null;var Hd=b.length&&
b[B].url;0!=v.depth&&Hd&&(L=b[B]);var R=new Jc(v,L);if(R.h){var Id=R.h.url||"";g.g.push(4);g.h[4]=Mc("top",Id)}var db={url:R.g.url||""};if(R.g.url){var eb=R.g.url.match(cc),rc=eb[1],sc=eb[3],tc=eb[4];v="";rc&&(v+=rc+":");sc&&(v+="//",v+=sc,tc&&(v+=":"+tc));var uc=v}else uc="";db=[db,{url:uc}];g.g.push(5);g.h[5]=db;Uc(this.i,e,g,this.j,c)}catch(V){try{Uc(this.i,e,{context:"ecmserr",rctx:a,msg:gd(V),url:R&&R.g.url},this.j,c)}catch(ge){}}return!0};
function gd(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);for(var c;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(d){}}return b};function id(a){var b="L";if(a.L&&a.hasOwnProperty(b))return a.L;b=new a;return a.L=b};function jd(){this.g=function(){return[]}};var Tc,fd,dd=new ad;function kd(){if(!window.google_measure_js_timing){var a=dd;a.g=!1;a.h!=a.i.google_js_reporting_queue&&($c()&&Fa(a.h,bd),a.h.length=0)}}(function(a){Tc=null!=a?a:new Rc;"number"!==typeof window.google_srt&&(window.google_srt=Math.random());Sc();fd=new cd;fd.h=function(b){var c=yc;0!==c&&(b.jc=String(c),b.shv=zc(c))};fd.j=!0;"complete"==window.document.readyState?kd():dd.g&&ac(window,"load",function(){kd()})})();function ld(a,b){return hd(a,b)}
function md(a){var b=id(jd).g();!a.eid&&b.length&&(a.eid=b.toString());Uc(Tc,"gdn-asoch",a,!0)};function Z(){var a=void 0===a?z:a;return a.oneAfmaInstance};function nd(a,b){b=Q(a,2)||b;if(!b)return"";if(O(a,13))return b;var c=/[?&]adurl=([^&]+)/.exec(b);if(!c)return b;var d=[b.slice(0,c.index+1)];Fb(a,4).forEach(function(e,g){d.push(encodeURIComponent(g)+"="+encodeURIComponent(e)+"&")});d.push(b.slice(c.index+1));return d.join("")}
function od(a,b){b=void 0===b?[]:b;b=0<b.length?b:Gc("data-asoch-targets");a=Fb(a,1,Rb);for(var c=[],d=0;d<b.length;++d){for(var e=b[d].getAttribute("data-asoch-targets"),g=e.split(","),f=!0,h=w(g),k=h.next();!k.done;k=h.next())if(!a.has(k.value)){f=!1;break}if(f){f=a.get(g[0]);for(e=1;e<g.length;++e){h=a.get(g[e]);f=Db(f).toJSON();h=h.toJSON();k=Math.max(f.length,h.length);for(var l=0;l<k;++l)null==f[l]&&(f[l]=h[l]);f=new Rb(f)}g=Fb(f,4);null!=K(f,5)&&g.set("nb",N(f,5,0).toString());c.push({element:b[d],
data:f})}else md({type:1,data:e})}return c}
function pd(a,b,c,d){c=nd(b,c);if(0<c.length){var e=c;var g=e.search(ic),f;b:{for(f=0;0<=(f=e.indexOf("ase",f))&&f<g;){var h=e.charCodeAt(f-1);if(38==h||63==h)if(h=e.charCodeAt(f+3),!h||61==h||38==h||35==h)break b;f+=4}f=-1}if(0>f)e=null;else{h=e.indexOf("&",f);if(0>h||h>g)h=g;e=decodeURIComponent(e.slice(f+4,-1!==h?h:0).replace(/\+/g," "))}"1"==e&&(e=609===d?4:"attributionReporting"in X?6:5,g=qd(c,"asr","1"),a.setAttribute("attributionsrc",g),c=qd(c,"nis",e.toString()));Xa(a,Dc(c,Ec(d)));a.target||
(a.target=null!=K(b,11)?Q(b,11):"_top")}}function rd(a){var b=void 0===b?"":b;a=w(a);for(var c=a.next();!c.done;c=a.next()){var d=c.value;c=d.data;var e=0===b.length?!1:d.element.matches(b);"A"!=d.element.tagName||O(c,1)||e||(d=d.element,pd(d,c,d.href,609))}}function sd(a){var b=Z();if(b){a=w(a);for(var c=a.next();!c.done;c=a.next())if((c=c.value.data)&&null!=K(c,8)){var d=Q(P(c,Tb,8),4);if(d){b.fetchAppStoreOverlay(d,void 0,Q(P(c,Tb,8),6));break}}}}
function td(a,b){function c(h,k){if(k){h=w(e);for(var l=h.next();!l.done;l=h.next())l=l.value,k[l.A()]&&l.N(!0)}}b=void 0===b?500:b;var d=[],e=[];a=w(a);for(var g=a.next();!g.done;g=a.next())(g=g.value.data)&&null!=K(g,12)&&(e.push(P(g,U,12)),d.push(P(g,U,12).A()));a=Z();d=w(d);for(g=d.next();!g.done;g=d.next()){g=g.value;var f=void 0;null==(f=a)||f.canOpenAndroidApp(g,c,function(){},b)}}
function ud(a,b,c,d,e){if(a||!b||null==K(b,12))return!1;var g=P(b,U,12).A();a="";if(0<Gb(b,T,7).length)for(var f=w(Gb(b,T,7)),h=f.next();!h.done;h=f.next())h=h.value,a+=Q(h,2)+" "+h.A()+" ";if(O(P(b,U,12),2))return vd({id:"gmob-apps",event:"och-open-android-app-before-click",deepLinks:a,appId:g,isDeepLinkPath:!1,exptIds:e}),d.click(c),d.openAndroidApp(g),setTimeout(function(){vd({id:"gmob-apps",event:"och-open-android-app",appId:g,isDeepLinkPath:!1,exptIds:e})},1E3),!0;vd({id:"gmob-apps",event:"och-open-android-app-validated-false",
deepLinks:a,appId:g,isDeepLinkPath:!1,exptIds:e});return!1}
function wd(a,b,c,d,e,g,f){function h(n){return xc(X,n)}function k(n){return e.openStoreOverlay(n,void 0,Q(l,6))}if(!c||null==K(c,8))return!1;var l=P(c,Tb,8),m=Q(l,2);Fb(c,10).forEach(function(n,p){var t=m;p=encodeURIComponent(p);var v=encodeURIComponent(n);n=new RegExp("[?&]"+p+"=([^&]+)");var B=n.exec(t);console.log(B);p=p+"="+v;m=B?t.replace(n,B[0].charAt(0)+p):t.replace("?","?"+p+"&")});vd({id:"gmob-apps",event:"och-try-u2-redirect",appId:Q(l,4)||"",isIos:a,isDeepLinkPath:!1,exptIds:g});xd(c)&&
O(c,15)&&!/[?&]label=/.test(d)&&(d=qd(d,"label","deep_link_fallback"));return e.redirectForStoreU2({clickUrl:d,trackingUrl:Q(l,3),finalUrl:m,pingFunc:f?h:e.click,openFunc:(null==b?0:O(b,1))?k:e.openIntentOrNativeApp})}function yd(a,b){b=void 0===b?null:b;if(null!==b){var c=new wa({url:a});if(c.h&&c.i||c.l)return b(xa(c)),Aa(c,1)}else return b=new wa({url:a,O:{}.O}),b.h&&b.i||b.l?navigator.sendBeacon?navigator.sendBeacon(xa(b),"")?Aa(b,1):Aa(b,2):Aa(b,0):a;return a}
function vd(a){var b=bc();b=null!=b?"="+encodeURIComponent(String(b)):"";b=fc("https://pagead2.googlesyndication.com/pagead/gen_204","zx"+b);zd(jc(b,a))}function zd(a,b){(void 0===b||b)&&X.fetch?X.fetch(a,{method:"GET",keepalive:!0,mode:"no-cors"}).then(function(c){c.ok||vc(X,a)}):vc(X,a)}function qd(a,b,c){b=encodeURIComponent(String(b));c=encodeURIComponent(String(c));return a.replace("?","?"+b+"="+c+"&")}
function xd(a){a=w(Gb(a,T,7));for(var b=a.next();!b.done;b=a.next())if(b=b.value,3===N(b,1,0)&&Q(b,2))return!0;return!1};var Ad=new function(a,b){this.g=a;this.defaultValue=void 0===b?!1:b}(434462125,!0);function Bd(){var a={};this.g=function(){var b=Ad.g,c=Ad.defaultValue;return null!=a[b]?a[b]:c}};function Cd(a){S.call(this,a,-1,Dd)}x(Cd,S);function Ed(a,b){return M(a,2,b)}function Fd(a,b){return M(a,3,b)}function Gd(a,b){return M(a,4,b)}function Jd(a,b){return M(a,5,b)}function Kd(a,b){return M(a,9,b)}function Ld(a,b){var c=void 0===c?!1:c;qb(a);if(b){var d=G([]);for(var e=0;e<b.length;e++)d[e]=b[e].v();a.g||(a.g={});a.g[10]=b}else a.g&&(a.g[10]=void 0),d=pb;return M(a,10,d,c)}function Md(a,b){return M(a,11,b)}function Nd(a,b){return M(a,1,b)}function Od(a){S.call(this,a)}x(Od,S);
var Dd=[10,6];var Pd="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function Qd(a){var b;return null!=(b=a.google_tag_data)?b:a.google_tag_data={}}
function Rd(a){var b,c;if("function"!==typeof(null==(b=a.navigator)?void 0:null==(c=b.userAgentData)?void 0:c.getHighEntropyValues))return null;var d=Qd(a);if(d.uach_promise)return d.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(Pd).then(function(e){null!=d.uach||(d.uach=e);return e});return d.uach_promise=a}
function Sd(a){var b;return Md(Ld(Kd(Jd(Gd(Fd(Ed(Nd(new Cd,a.platform||""),a.platformVersion||""),a.architecture||""),a.model||""),a.uaFullVersion||""),a.bitness||""),(null==(b=a.fullVersionList)?void 0:b.map(function(c){var d=new Od;d=M(d,1,c.brand);return M(d,2,c.version)}))||[]),a.wow64||!1)}
function Td(){var a=window;if(id(Bd).g()){var b,c;return null!=(c=null==(b=Rd(a))?void 0:b.then(function(f){return Sd(f)}))?c:null}var d,e;if("function"!==typeof(null==(d=a.navigator)?void 0:null==(e=d.userAgentData)?void 0:e.getHighEntropyValues))return null;var g;return null!=(g=a.navigator.userAgentData.getHighEntropyValues(Pd).then(function(f){return Sd(f)}))?g:null};function Ud(a){var b=this;this.l=bb||$a||cb||ab;var c=Gc("data-asoch-meta");if(1!==c.length)md({type:2,data:c.length});else{this.D=70;this.h=new Ub(JSON.parse(c[0].getAttribute("data-asoch-meta"))||[]);this.K=a["extra-meta"]?new Ub(JSON.parse(a["extra-meta"])):null;this.C="true"===a["is-fsn"];this.j=a["ios-store-overlay-config"]?new Wb(JSON.parse(a["ios-store-overlay-config"])):null;this.S="true"===a["use-cct-over-browser"];this.o=a["expt-ids"]||"";this.P="true"===a["send-ac-click-ping-by-js"];this.H=
"true"===a["correct-redirect-url-for-och-15-click"];this.R="true"===a["send-click-ping-by-js-in-och"];this.B="";c=Td();null!=c&&c.then(function(e){e=Jb(e);for(var g=[],f=0,h=0;h<e.length;h++){var k=e.charCodeAt(h);255<k&&(g[f++]=k&255,k>>=8);g[f++]=k}e=ib(g,3);b.B=e});this.g=od(this.h);this.T=Number(a["deeplink-and-android-app-validation-timeout"])||500;this.F=-Infinity;this.i=Q(this.h,5)||"";this.G=O(this.h,11);this.K&&(this.G=O(this.K,11));this.u=this.s=null;O(this.h,3)||(rd(this.g),M(this.h,3,
!0));Vd(this.g);a=Z();!this.l&&a&&td(this.g,this.T);var d;if(a&&(null==(d=this.j)?0:O(d,2)))switch(d=function(){var e=N(b.j,4,0);0<e?z.setTimeout(function(){sd(b.g)},e):sd(b.g)},N(this.j,3,0)){case 1:a.runOnOnShowEvent(d);break;case 2:pc(d);break;default:sd(this.g)}ac(W,"click",ld(557,function(e){a:if(!e.defaultPrevented||b.s===e){for(var g,f,h=e.target;(!g||!f)&&h;){f||"A"!=h.tagName||(f=h);var k=h.hasAttribute("data-asoch-targets"),l=h.hasAttribute("data-asoch-fixed-value");if(!g)if(l)g=new Rb(JSON.parse(h.getAttribute("data-asoch-fixed-value"))||
[]);else if("A"==h.tagName||k)if(k=k&&"true"===h.getAttribute("data-asoch-is-dynamic")?od(b.h,[h]):b.g,k=Wd(k,h))g=k.data;h=h.parentElement}if(h=g&&!O(g,1)){if(e.defaultPrevented){k=g;if(b.s===e&&b.u){g=new Pb(b.u);h=Q(k,9);l="";switch(N(g,4,1)){case 2:if(N(g,2,0))l="blocked_fast_click";else if(Q(g,1)||Q(g,7))l="blocked_border_click";break;case 3:var m=void 0===m?W:m;m=m.getElementById?m.getElementById("common_15click_anchor"):null;"function"===typeof window.copfcChm&&m&&(k=Db(k),M(k,5,12),Fb(k,4).set("nb",
(12).toString()),(l=Wd(b.g,m))?l.data=k:b.g.push({element:m,data:k}),!b.H&&f&&(Xd(b,e,f,k),M(k,2,f.href)),window.copfcChm(e,nd(k,m.href),null,null!=K(g,10)?Jb(P(g,Qb,10)):null),b.H&&Xd(b,e,m,k));l="onepointfiveclick_first_click"}h&&l&&zd(h+"&label="+l,!1);Bc(b.D)}break a}m=w(Eb(g,6));for(k=m.next();!k.done;k=m.next())zd(k.value)}if(f&&h){m=f;g=h?g:null;(f=Wd(b.g,m))?f=f.data:(f=new Rb,M(f,2,m.href),M(f,11,m.target||"_top"),b.g.push({element:m,data:f}));pd(m,g||f,Q(f,2),557);Xd(b,e,m,g);f=w(Eb(b.h,
17));for(k=f.next();!k.done;k=f.next()){h=void 0;l=k.value;var n=W.body;h=void 0===h?{}:h;"function"===typeof window.CustomEvent?k=new CustomEvent(l,h):(k=document.createEvent("CustomEvent"),k.initCustomEvent(l,!!h.bubbles,!!h.cancelable,h.detail));n.dispatchEvent(k)}O(b.h,16)||b.C?Yd(b,e,m,g):(f="",(h=Z())&&(f=h.appendClickSignals(m.href)),Zd(b,e,m,g,f))}}}),Xb);this.i&&"function"===typeof window.ss&&ac(W.body,"mouseover",ld(626,function(){window.ss(b.i,0)}),Yb);d=window;d.googqscp&&"function"===
typeof d.googqscp.registerCallback&&d.googqscp.registerCallback(function(e,g){b.s=e;b.u=g})}}function Yd(a,b,c,d){var e,g,f;ta(new sa(new pa(function(h){switch(h.g){case 1:e="";g=Z();if(!g){h.g=2;break}var k=g.appendClickSignalsAsync(c.href);h.g=3;return{value:k};case 3:e=h.l||"";if(!a.C){h.g=2;break}k=g.getNativeClickMeta();h.g=5;return{value:k};case 5:if(f=h.l){if(f.customClickGestureEligible)return h.return();e=qd(e,"nas",f.encodedNas)}case 2:Zd(a,b,c,d,e),h.g=0}})))}
function Zd(a,b,c,d,e){var g=O(a.h,2),f=g&&300<Date.now()-a.F,h=Z();if(h){if(b.preventDefault?b.preventDefault():b.returnValue=!1,e=h.logScionEventAndAddParam(e),!ud(a.l,d,e,h,a.o)&&!wd(a.l,a.j,d,e,h,a.o,a.P)){c=a.S;b=a.l;var k=a.o,l=a.R,m=O(d,15),n=!/[?&]dsh=1(&|$)/.test(e)&&/[?&]ae=1(&|$)/.test(e);!g||!f||m&&n||(e=(void 0===l?0:l)?yd(e):yd(e,h.click));e&&e.startsWith("intent:")?(h.openIntentOrNativeApp(e),vd({id:"gmob-apps",event:"och-open-intent-or-native-app",appId:null!=K(d,8)&&Q(P(d,Tb,8),4)||
"",isIos:b,isDeepLinkPath:!1,exptIds:k})):c?b?h.openBrowser(e):h.openChromeCustomTab(e):h.openSystemBrowser(e,{useFirstPackage:!0,useRunningProcess:!0})}}else d=window,d.pawsig&&"function"===typeof d.pawsig.clk?d.pawsig.clk(c):f&&(d=yd(c.href),d!==c.href&&Xa(c,Dc(d,Ec(599))));f&&(a.F=Date.now());Bc(a.D)}
function Xd(a,b,c,d){if(!O(d,13)){var e=c.href;var g=/[?&]adurl=([^&]+)/.exec(e);e=g?[e.slice(0,g.index),e.slice(g.index)]:[e,""];for(Xa(c,Dc(e[0],Ec(557)));!c.id;)if(g="asoch-id-"+bc(),!W.getElementById(g)){c.id=g;break}g=c.id;"function"===typeof window.xy&&window.xy(b,c,W.body);"function"===typeof window.mb&&window.mb(c);"function"===typeof window.bgz&&window.bgz(g);"function"===typeof window.ja&&window.ja(g,d?N(d,5,0):0);a.i&&"function"===typeof window.ss&&(a.G?window.ss(g,1,a.i):window.ss(a.i,
1));0<e.length&&(a=0<a.B.length?c.href+"&uach="+encodeURIComponent(a.B)+e[1]:c.href+e[1],Xa(c,Dc(a,Ec(557))))}}function $d(a){oc(ld(556,function(){new Ud(a||{})}))}function Wd(a,b){return Ga(a,function(c){return c.element===b})}function Vd(a){a=w(a);for(var b=a.next();!b.done;b=a.next()){var c=b.value;"A"==c.element.tagName&&(b=c.element,c=c.data,null!=K(c,2)||M(c,2,b.href))}};var ae=ld(555,function(a){return $d(a)});yc=70;var be=Ac(70);if(null==be)throw Error("JSC not found 70");for(var ce={},de=be.attributes,ee=de.length-1;0<=ee;ee--){var fe=de[ee].name;0===fe.indexOf("data-jcp-")&&(ce[fe.substring(9)]=de[ee].value)}ae(ce);}).call(this);
